[tool.poetry]
name = "preop-covid"
version = "0.1.0"
description = ""
authors = ["Philip Chung <philip.f.chung@gmail.com>"]
readme = "README.md"
packages = [{include = "preop_covid"}]

[tool.poetry.dependencies]
python = "^3.10"
pip = "^22.3.1"
pandas = "^1.5.1"
jupyter = "^1.0.0"
black = "^22.10.0"
flake8 = "^5.0.4"
matplotlib = "^3.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
